global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    platform: ardmatrix-aiops
    environment: demo

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: grafana
    metrics_path: /metrics
    static_configs:
      - targets: ["grafana:3000"]

  - job_name: inventory-watcher
    static_configs:
      - targets: ["inventory-watcher:8000"]

  - job_name: inventory-consumer
    static_configs:
      - targets: ["inventory-consumer:8000"]

  - job_name: source-ingestion-api
    static_configs:
      - targets: ["source-ingestion-api:8000"]

  - job_name: source-file-watcher
    static_configs:
      - targets: ["source-file-watcher:8000"]

  - job_name: kafka-traffic-simulator
    static_configs:
      - targets: ["kafka-traffic-simulator:8000"]

  - job_name: ai-event-consumer
    static_configs:
      - targets: ["ai-event-consumer:8000"]

  - job_name: infrastructure-metric-consumer
    static_configs:
      - targets: ["infrastructure-metric-consumer:8000"]

  - job_name: server-metric-publisher
    static_configs:
      - targets: ["server-metric-publisher:8000"]

  - job_name: server-metric-consumer
    static_configs:
      - targets: ["server-metric-consumer:8000"]
