apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: TimescaleDB
    orgId: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 3.5.0
      timeInterval: 15s

  - name: TimescaleDB
    uid: timescaledb
    type: postgres
    access: proxy
    url: timescaledb:5432
    user: ${POSTGRES_USER}
    database: ${POSTGRES_DB}
    editable: false
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: disable
      postgresVersion: 1700
      timescaledb: true
      maxOpenConns: 20
      maxIdleConns: 5
      connMaxLifetime: 14400
